### ISSUE TITLE
Currently this nuget generates warning when used with strongly named assemblies project

### ISSUE THREAD

**Issue by marik91** [HavenDV/Hardcodet.NotifyIcon.Wpf.NetCore#1]
Warning CS8002: Referenced assembly 'Hardcodet.Wpf.TaskbarNotification, Version=1.0.11.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

Could you add code signing so it would be strongly named?

**Comment by HavenDV** [comment]
Added.
